### ISSUE TITLE
SQL inserts fail if strings overflow maximum lengths if ANSI_WARNINGS is enabled

### ISSUE THREAD

**Issue by nyetwurk** [kawf/kawf#28]
The postform was changed in 45b6c4e, but there are still plenty of ways to overflow the various string fields on insert, eg:

PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'url' at row 1' in /usr/local/kawf/include/sql.inc:51
Stack trace:
#0 /usr/local/kawf/include/sql.inc(51): PDOStatement->execute(Array)
#1 /usr/local/kawf/include/sql.inc(68): db_query('insert into f_m...', Array)
#2 /usr/local/kawf/user/postmessage.inc(127): db_exec('insert into f_m...', Array)
#3 /usr/local/kawf/user/post.php(265): postmessage(Object(ForumUser), '5', Array, Array)
#4 /usr/local/kawf/user/main.php(313): include_once('/usr/local/kawf...')
#5 /usr/local/kawf/config/index.php(51): include('/usr/local/kawf...')
#6 {main}
  thrown in /usr/local/kawf/include/sql.inc on line 51

Either we need to turn off ANSI_WARNINGS, or ALL SQL strings have to be checked before insertion.

**Comment by nyetwurk** [comment]
This has the unfortunate result of messages in the DB that do not belong to a thread:

`select mid,tid from f_messages5 where not exists (select 1 from f_threads5 where f_messages5.tid = f_threads5.tid);`

We will need a way to 1) find a free thread id 2) attach them to a thread, once this bug is fixed.

**Comment by nyetwurk** [comment]
It is easy enough to simply silently truncate urltxt, but the user should be warned if url, imageurl, or video is too long

**Comment by nyetwurk** [comment]
Still need to add try/catch around the insert to make sure we don't have orphaned messages if this check fails.. eg. maybe something got longer due to post processing (maybe utf8 to multibyte?)
